route:
  group_by: ['job','instance']

  group_wait: 5s
  group_interval: 10s
  repeat_interval: 15s

  receiver: discord

receivers:
- name: discord
  discord_configs:
  - webhook_url: 'https://discord.com/api/webhooks/1177986692473434193/Vbz8JfmmcyohQcrZK2rwSaIx09wbfqq2gCANfkdkBo2XOMAv_pCEWlvKzspKFTWu-h4-'
